Golsoft/Golsoft/urls.py
from django.contrib import admin
from django.urls import path,include
from dashboard import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', views.IndexView.as_view()),
    path(r'dashboard/', include('dashboard.urls', namespace='dashboard')),
]

Golsoft/dashboard/urls.py
from django.urls import path
from dashboard import views
from MIR_API import APIs_Manager

app_name = 'basic_app'
APIs_Manager.start()
urlpatterns = [
    # generla views
    path(r'robot', views.RobotsListView.as_view(), name='list'),
    path(r'missions', views.MissionsListView.as_view(), name='misisons'),
    path(r'configuration', views.configuration.as_view(), name='configuration'),
    path(r'get_more_tables', views.get_more_tables.as_view(), name='get_more_tables'),
    # robot show view
    path(r'change_state', views.change_state, name='change_state'),
    # missions views
    path(r'get_new_missions', views.get_new_missions, name='get_new_missions'),
    path(r'add_mission_url', views.add_mission_url, name='add_mission_url'),
    path(r'cancel_mission_url', views.cancel_mission_url,
         name='cancel_mission_url'),
    # missions views
    path(r'enter_robot_data', views.enter_robot_data, name='enter_robot_data'),
    path(r'remove_robot_data', views.remove_robot_data, name='remove_robot_data'),

    # statistics views
    path(r'statistics', views.statistics.as_view(), name='statistics'),

    # Golbox
    path(r'golbox', views.Golbox.as_view(), name='golbox'),
]

Golsoft/dashboard/models.py
from django.db import models
from datetime import datetime
from django.urls import reverse


# Create your models here.
class Robot(models.Model):
    model = models.CharField(max_length=150, default="none")
    robot_name = models.CharField(max_length=150, default="none")
    auth = models.CharField(max_length=150, default="none")
    ip = models.CharField(max_length=150, default="none")
    verification = models.BooleanField(default=False)

    def __str__(self):
        return self.robot_name


class RStatus(models.Model):
    robot = models.ForeignKey(
        Robot, related_name='robot', on_delete=models.CASCADE, default=1)
    battery = models.DecimalField(max_digits=12, decimal_places=2, default=1)
    posx = models.DecimalField(max_digits=12, decimal_places=2, default=1)
    posy = models.DecimalField(max_digits=12, decimal_places=2, default=1)
    orientation = models.DecimalField(
        max_digits=12, decimal_places=2, default=1)
    state = models.IntegerField()  # 1 ready 0 stop
    statetext = models.CharField(
        max_length=150, default="none")  # 1 ready 0 stop
    velocity_l = models.DecimalField(
        max_digits=12, decimal_places=2, default=1)
    velocity_a = models.DecimalField(
        max_digits=12, decimal_places=2, default=1)
    mission_queue_id = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.robot.robot_name


class Missions(models.Model):
    id_mission = models.CharField(max_length=150, unique=True)
    name = models.CharField(max_length=150, unique=True)
    url = models.CharField(max_length=150)

    def __str__(self):
        return self.name


class Mission_queue(models.Model):
    mission = models.ForeignKey(
        Missions, related_name='asigned_mission', on_delete=models.CASCADE)
    asigned_robot = models.ForeignKey(
        Robot, related_name='asigned_robot', on_delete=models.CASCADE, null=True, blank=True)
    mision_state = models.IntegerField()  # 3cancelled 2 executing 1 assigned 0 stop 4 finsh
    robot_queue_id = models.IntegerField(null=True, blank=True)
    time_request = models.DateTimeField(auto_now=True)

    def filter_status(self):
        return self.mision_state.orderby(mision_state).all()

    def __str__(self):
        return self.mission.name


class GolsBox(models.Model):
    ip = models.CharField(max_length=150, default="none")
    verification = models.BooleanField(default=False)
    SW1_mode = models.IntegerField(default=2)  # 0 for interrupt 1 for smart SW
    SW1_state = models.BooleanField(default=False)
    SW2_mode = models.IntegerField(default=2)  # 0 for interrupt 1 for smart SW
    SW2_state = models.BooleanField(default=False)
    SW3_mode = models.IntegerField(default=2)  # 0 for interrupt 1 for smart SW
    SW3_state = models.BooleanField(default=False)
    SW4_mode = models.IntegerField(default=2)  # 0 for interrupt 1 for smart SW
    SW4_state = models.BooleanField(default=False)
    SW1_mission = models.ForeignKey(
        Missions, related_name='asigned_mission1', on_delete=models.CASCADE, null=True, blank=True)
    SW2_mission = models.ForeignKey(
        Missions, related_name='asigned_mission2', on_delete=models.CASCADE, null=True, blank=True)
    SW3_mission = models.ForeignKey(
        Missions, related_name='asigned_mission3', on_delete=models.CASCADE, null=True, blank=True)
    SW4_mission = models.ForeignKey(
        Missions, related_name='asigned_mission4', on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.ip

Golsoft/dashboard/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponse
from django.views.generic import (View, TemplateView,
                                  ListView, DetailView,
                                  CreateView, DeleteView,
                                  UpdateView)

from . import models
from itertools import chain
from MIR_API import APIs_Manager


class IndexView(TemplateView):
    # Just set this Class Object Attribute to the template page.
    # template_name = 'app_name/site.html'
    template_name = 'dashboard/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['injectme'] = "GOLSLEY SOFTWARE FOR MIR ROBOTS"
        return context


class Golbox(ListView):
    # Just set this Class Object Attribute to the template page.
    # template_name = 'app_name/site.html'
    template_name = 'dashboard/golbox.html'

    model = models.GolsBox

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['injectme'] = models.Missions.objects.all()
        return context


class RobotsListView(ListView):
    # If you don't pass in this attribute,
    # Django will auto create a context name
    # for you with object_list!
    # Default would be 'school_list'

    # Example of making your own:
    # context_object_name = 'schools'
    template_name = 'dashboard/robots.html'
    model = models.Robot

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        field = models.Robot.objects.all()
        queryset_list = set()

        for robots in field:
            field_ = getattr(robots, 'robot_name')
            queryset_list.add(models.RStatus.objects.filter(
                robot__robot_name=str(field_)).order_by('-id').first())

        context['injectme'] = queryset_list
        return context


class MissionsListView(ListView):
    template_name = 'dashboard/Missions.html'
    model = models.Missions

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['injectme'] = models.Mission_queue.objects.order_by(
            '-mision_state').all()
        return context


class configuration(ListView):
    model = models.Robot
    template_name = 'dashboard/configuration.html'


class get_more_tables(TemplateView):
    model = models.Robot
    template_name = 'dashboard/get_more_tables.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        field = models.Robot.objects.all()
        queryset_list = set()
        for robots in field:
            field_ = getattr(robots, 'robot_name')
            queryset_list.add(models.RStatus.objects.filter(
                robot__robot_name=str(field_)).order_by('-id').first())

        context['injectme'] = queryset_list
    
        return context


def change_state(request):
    robot_id = int(request.GET['robot_id'])
    robot = models.Robot.objects.get(id=robot_id)
    robot_state = models.RStatus.objects.filter(
        robot__id=str(robot_id)).order_by('-id').first()
    if(robot_state.state == 4):
        APIs_Manager.Add_Job('put_state', robot, 1)
    else:
        APIs_Manager.Add_Job('put_state', robot, 0)
    # call the api here with the correct id
    return HttpResponse("OK")


def get_new_missions(request):
    robot_name = "MiR_R165"
    robot = models.Robot.objects.get(robot_name=robot_name)
    APIs_Manager.Add_Job('get_missions', robot)

    # call the api to get new mission list!

    return HttpResponse("OK")


def add_mission_url(request):
    mission_id = str(request.GET['mission_id'])
    mission_model = models.Missions.objects.get(id_mission=mission_id)

    new = models.Mission_queue(mission=mission_model, mision_state=0)
    new.save()
    user_dict_ = models.Mission_queue.objects.order_by('-mision_state').all()
    user_dict = {"injectme": user_dict_}
    return render(request, 'dashboard/Missions_queue.html', context=user_dict)


def cancel_mission_url(request):
    mission_queue_id = int(request.GET['mission_queue_id'])
    mode_mission_queue = models.Mission_queue.objects.get(id=mission_queue_id)
    mode_mission_queue.mision_state = -1
    mode_mission_queue.save()
    user_dict_ = models.Mission_queue.objects.order_by('-mision_state').all()
    user_dict = {"injectme": user_dict_}
    return render(request, 'dashboard/Missions_queue.html', context=user_dict)


def enter_robot_data(request):
    robot_ip = str(request.GET['robot_ip'])
    robot_auth = str(request.GET['robot_auth'])
    new = models.Robot(ip=robot_ip, auth=robot_auth)
    new.save()
    user_dict_ = models.Robot.objects.all()
    user_dict = {"injectme": user_dict_}
    return render(request, 'dashboard/robot_info.html', context=user_dict)


def remove_robot_data(request):
    robot_id = int(request.GET['robot_id'])
    models.Robot.objects.get(id=robot_id).delete()
    user_dict_ = models.Robot.objects.all()
    user_dict = {"injectme": user_dict_}
    return render(request, 'dashboard/robot_info.html', context=user_dict)


class statistics(ListView):

    template_name = 'dashboard/statistics.html'
    model = models.Missions

Golsoft/templates/dashboard/Missions.html
<!DOCTYPE html>
{% extends "dashboard/base.html" %}
{% load staticfiles %}
    {% block body_block%}
    <div class="container">
       <div class ="row">
           <div class = "col">
               <table class="table">
                   <h2>MISSIONS AVIABLE</h2>
                    <thead>
                        <tr>
                            <th scope="col">id</th>
                            <th scope="col">Name</th>
                            <th scope="col">Launch!</th>
                        </tr>
                    </thead>
                   <tbody>
                   {%for mission in missions_list%}
                        <tr>
                            <td scope="row">{{mission.id_mission}}</td>
                            <td>{{mission.name}}</td>
                            <td><button type="button" class="btn btn-primary addMission" member_id= "{{mission.id_mission}}">Launch Mission {{mission.id_mission}}</button></td>
                        </tr>
                   {%endfor%}
                   </tbody>
               </ul>
            </table>
            <td><button type="button" class="btn btn-primary updateMissons" id= "refresh">Refresh Robot Missons</button></td>
           </div>
          
           <div class="col "">
                <table class="table">
                    <h2>MISSIONS QUEUE</h2>
                    <thead>
                        <tr>
                            <th scope="col">Name</th>
                            <th scope="col">Robot</th>
                            <th scope="col">State</th>
                            <th scope="col">ABORT</th>
                            <th scope="col">Request Time</th>
                        </tr>
                    </thead>
                   <tbody id="_appendHere">
                   {%for mission in injectme%}
                        <tr >
                            <td scope="row">{{mission.mission}}</td>
                            <td>{{mission.asigned_robot.robot_name}}</td>
                            {%if mission.mision_state  == 1%}
                            <td>Asigned</td>
                            <td></td>
                            {%elif mission.mision_state  == 2%}
                            <td>Working</td>
                            <td></td>
                            {%elif mission.mision_state  == 4%}
                            <td>Finsih</td>
                            <td></td>
                            {%elif mission.mision_state  == 0%}
                            <td>Waiting robot</td>
                            <td><button type="button" class="btn btn-danger abort" member_id= "{{mission.id}} ">ABORT</button></td>
                            {%elif mission.mision_state  == -1%}
                            <td>Aborted</td>
                            <td></td>
                            {%else %}
                            <td>ERROR</td>
                            <td></td>
                            {%endif %}  
                            <td>{{ mission.time_request| date:"jS F H:i:s"}}</td>                   
                        </tr>
                   {%endfor%}
                   </tbody>
               </ul>
            </table>
            </div>
       </div>
    </div>
</script>
    <script>
    var new_mission_url = " {% url 'dashboard:get_new_missions' %}" 
    var add_mission_url = " {% url 'dashboard:add_mission_url' %}" 
    var cancel_mission_url = " {% url 'dashboard:cancel_mission_url' %}" 
    </script>
    <script src="{% static "dashboard/mission.js" %}" ></script>
    {% endblock %}

Golsoft/templates/dashboard/Missions_queue.html
{%for mission in injectme%}
                        <tr >
                            <td scope="row">{{mission.mission}}</td>
                            <td>{{mission.asigned_robot.robot_name}}</td>
                            {%if mission.mision_state  == 1%}
                            <td>Asigned</td>
                            <td></td>
                            {%elif mission.mision_state  == 2%}
                            <td>Working</td>
                            <td></td>
                            {%elif mission.mision_state  == 4%}
                            <td>Finsih</td>
                            <td></td>
                            {%elif mission.mision_state  == 0%}
                            <td>Waiting robot</td>
                            <td><button type="button" class="btn btn-danger abort" member_id= "{{mission.id}} ">ABORT</button></td>
                            {%elif mission.mision_state  == -1%}
                            <td>Aborted</td>
                            <td></td>
                            {%else %}
                            <td>ERROR</td>
                            <td></td>
                            {%endif %}  
                            <td>{{ mission.time_request| date:"jS F H:i:s"}}</td>                         
                        </tr>
                   {%endfor%}

Golsoft/templates/dashboard/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8" />
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="{%static "dashboard/bootstrap.min.css" %} " >
  </head>
  <body>
    <ul class="nav justify-content-start ">
      <li class="nav-item">
        <a class="nav-link active" href="{% url 'dashboard:list' %}"> Robots</a>
      </li>
      <li class="nav-item">
        <a class="nav-link active" href="{% url 'dashboard:misisons' %}">
          Missions
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'dashboard:configuration' %}"
          >Configuration</a
        >
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'dashboard:statistics' %}"
          >Statistics</a
        >
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'dashboard:golbox' %}">GolBox_test</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
      </li>
    </ul>
    <div class="container">
      <script
        src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"
      ></script>
      <script
        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"
      ></script>
      <script
        src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"
      ></script>
      <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

      {% load staticfiles%} {% block body_block %} {# Anything outside of this
      will be inherited if you use extend.#} {% endblock %}
    </div>
  </body>
</html>

Golsoft/templates/dashboard/configuration.html
<!DOCTYPE html>

{% extends "dashboard/base.html" %}
{% load staticfiles %}
    {% block body_block%}
        <div class="container">
            <div class="hadow-none p-3 mb-5 bg-light rounded">
                <div class="btn-group" role="group" aria-label="Basic example">
                    <button type="button" class="btn btn-primary">Robots</button>
                    <button type="button" class="btn btn-secondary">Plc</button>
                    <button type="button" class="btn btn-secondary">Smart Switchs</button>
                    <button type="button" class="btn btn-secondary">GolBox</button>
                </div>
            </div>
            <div class="container">
                    </dibv>
            <div class="row">
                <div class="col-4">
                    <form>
                        <h5 class="card-title">Add a new robot</h5>
                        <div class="form-group" id = "DynamicValueAssignedHere_2">
                            <label for="exampleFormControlInput1">Robot IP</label>
                            <input class="form-control form-control-lg" type="text" placeholder="Ex: http//:192.168.1.51" id ="robot_ip"> 
                        </div>
                        <div class="form-group" id = "DynamicValueAssignedHere_2">
                                <label for="exampleFormControlInput2">Robot AUTH</label>
                                <input class="form-control form-control-lg" type="text" placeholder="Auth Code" id ="robot_auth"> 
                        </div> 
                        <a href="#" class="btn btn-primary addrobotinfo">Enter Data</a>
                    </form>
                </div>
                <div class="col-8">
                    <table class="table">
                        <h2>ROBOTS AVIABLE</h2>
                        <thead>
                            <tr>
                                <th scope="col">id</th>
                                <th scope="col">Robot</th>
                                <th scope="col">Ip</th>
                                <th scope="col">Status</th>
                                <th scope="col">Remove Robot</th>
                            </tr>
                        </thead>
                        <tbody id="_appendHere">
                            {%for robots in robot_list%}
                                {% if robots.verification%}
                                <tr class="table-primary">
                                    <td scope="row">{{robots.id}}</td>
                                    <td>{{robots.robot_name}}</td>
                                    <td>{{robots.ip}}</td>
                                    <td>Correct!!</td>
                                {%else%}
                                <tr class="table-warning">
                                    <td scope="row">{{robots.id}}</td>
                                    <td>{{robots.robot_name}}</td>
                                    <td>{{robots.ip}}</td>
                                    <td>ERROR!!</td>                           
                                {%endif%}
                                    <td><button type="button" class="btn btn-danger removerobotinfo" member_id ="{{robots.id}}" >REMOVE ROBOT!</button></td> 
                                </tr>
                            {%endfor%}
                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    


    
    </script>
    <script>
        var enter_robot_data_url = " {% url 'dashboard:enter_robot_data' %}" 
        var remove_robot_data_url = " {% url 'dashboard:remove_robot_data' %}" 
    </script>
    <script src="{% static "dashboard/configuration.js" %}" ></script>
    {% endblock %}

Golsoft/templates/dashboard/get_more_tables.html
{% for Robot in injectme %} {% if Robot.robot.verification == True%}
<div class="col-sm">
  <div class="card" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title">{{ Robot.robot.robot_name }}</h5>
      <ul class="list-group">
        <li class="list-group-item" id="model" {{Robot.robot.model}}>
          Model: {{ Robot.robot.model }}
        </li>
        <li class="list-group-item">Battery: {{ Robot.battery }} %</li>
        <li class="list-group-item">State: {{ Robot.statetext }}</li>
        <li class="list-group-item">Linear Velocity: {{ Robot.velocity_l }}</li>
        {%if Robot.state == 4%}
        <button
          type="button"
          class="btn btn-primary updateButton"
          member_id="{{ Robot.robot.id }}"
        >
          Start
        </button>
        {%else%}
        <button
          type="button"
          class="btn btn-danger updateButton"
          member_id="{{ Robot.robot.id }}"
        >
          Stop
        </button>
        {%endif %}
      </ul>
    </div>
  </div>
</div>
{%endif %} {% endfor %}

Golsoft/templates/dashboard/golbox.html
<!DOCTYPE html>
{% extends "dashboard/base.html" %} {% block body_block%}
<table class="table">
  <thead>
    <tr>
      <th scope="col">SW_mode</th>
      <th scope="col">Sw_state</th>
      <th scope="col">Mission</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      {%if golsbox_list.0.SW1_mode == 1%}
      <th scope="row">Call Button</td>
      {%else %}
      <th scope="row">Sensor</td>
      {%endif%}
      <td>{{golsbox_list.0.SW1_state}}</td>
      {%if golsbox_list.0.SW1_mode == 1%}
      <td>
        <div class="form-group col-sm-6">
            <select id="inputState" class="form-control">
              <option selected>{{golsbox_list.0.SW1_mission}}</option>
              {%for mission in injectme%}
              <option>{{mission.name}}</option>
              {%endfor%}
            </select>
          </div>
      </td>
      {%else %}
      <td>NOT ABLE</td>
      {%endif%}
    </tr>
    <tr>
        {%if golsbox_list.0.SW2_mode == 1%}
        <th scope="row">Call Button</td>
        {%else %}
        <th scope="row">Sensor</td>
        {%endif%}
        <td>{{golsbox_list.0.SW2_state}}</td>
        {%if golsbox_list.0.SW2_mode == 1%}
      <td>
        <div class="form-group col-sm-6">
            <select id="inputState" class="form-control">
              <option selected>{{golsbox_list.0.SW2_mission}}</option>
              {%for mission in injectme%}
              <option>{{mission.name}}</option>
              {%endfor%}
            </select>
          </div>
      </td>
      {%else %}
      <td>NOT ABLE</td>
      {%endif%}
    </tr>
    <tr>
            {%if golsbox_list.0.SW3_mode == 1%}
            <th scope="row">Call Button</td>
            {%else %}
            <th scope="row">Sensor</td>
            {%endif%}
            <td>{{golsbox_list.0.SW3_state}}</td>
            {%if golsbox_list.0.SW3_mode == 1%}
      <td>
        <div class="form-group col-sm-6">
            <select id="inputState" class="form-control">
              <option selected>{{golsbox_list.0.SW3_mission}}</option>
              {%for mission in injectme%}
              <option>{{mission.name}}</option>
              {%endfor%}
            </select>
          </div>
      </td>
      {%else %}
      <td>NOT ABLE</td>
      {%endif%}
    </tr>
    <tr>
            {%if golsbox_list.0.SW4_mode == 1%}
            <th scope="row">Call Button</td>
            {%else %}
            <th scope="row">Sensor</td>
            {%endif%}
            <td>{{golsbox_list.0.SW4_state}}</td>
            {%if golsbox_list.0.SW4_mode == 1%}
      <td>
        <div class="form-group col-sm-6">
            <select id="inputState" class="form-control">
              <option selected>{{golsbox_list.0.SW4_mission}}</option>
              {%for mission in injectme%}
              <option>{{golsbox_list.0.SW4_mission}}</option>
              {%endfor%}
            </select>
          </div>
      </td>
      {%else %}
      <td>NOT ABLE</td>
      {%endif%}
    </tr>
  </tbody>
</table>
<button type="button" class="btn btn-primary">Update</button>

{% endblock %}

Golsoft/templates/dashboard/index.html
<!DOCTYPE html>
{% extends "dashboard/base.html" %}
    {% block body_block%}
<h1>{{injectme}}</h1>

    {% endblock %}

Golsoft/templates/dashboard/robots.html
<!DOCTYPE html>

{% extends "dashboard/base.html" %}
{% load staticfiles %}
    {% block body_block%}
    <div class="container">
        <div class="row" id="_appendHere">
            {% for Robot in injectme %}
            {% if Robot.robot.verification == True%}
            <div class="col-sm">
              <div class="card" style="width: 18rem;">
                <div class="card-body">
                  <h5 class="card-title">{{Robot.robot.robot_name}}</h5>
                    <ul class="list-group" >
                        <li class="list-group-item" id = "model"{{Robot.robot.model}}>Model: {{ Robot.robot.model }}</li>
                        <li class="list-group-item">Battery: {{ Robot.battery }} % </li>
                        <li class="list-group-item">State: {{ Robot.statetext }}  </li>
                        <li class="list-group-item">Linear Velocity: {{ Robot.velocity_l }}</li>
                        {%if Robot.state == 4%}
                        <button
                          type="button"
                          class="btn btn-primary updateButton"
                          member_id="{{ Robot.robot.id }}"
                        >
                          Start
                        </button>
                        {%else%}
                        <button
                          type="button"
                          class="btn btn-danger updateButton"
                          member_id="{{ Robot.robot.id }}"
                        >
                          Stop
                        </button>
                        {%endif %}
                    </ul>
                </div>
              </div>
            </div>
            {%endif %}
          {% endfor %}
       </div>
    </div>
    <script>
    setInterval(function() {
        $.ajax({
            type: "GET",
            url: "{% url 'dashboard:get_more_tables' %}",  // URL to your view that serves new info
        })
        .done(function(response) {
            $('#_appendHere').html(response);
        });
    }, 1000)
    
    </script>
    <script>
      var state_url = " {% url 'dashboard:change_state' %}" 
    </script>
     <script src="{% static "dashboard/robots.js" %}" ></script>
    {% endblock %}

Golsoft/templates/dashboard/statistics.html
<!DOCTYPE html>

{% extends "dashboard/base.html" %}
{% load staticfiles %}
    {% block body_block%}
        <div class="container">
            <div class="hadow-none p-3 mb-5 bg-light rounded">
                <div class="btn-group" role="group" aria-label="Basic example">
                    {%for missions in missions_list%}
                    {% if missions.name == "Line 2"%}
                    <button type="button" class="btn btn-primary">{{missions.name}}</button>
                    {%else%}
                    <button type="button" class="btn btn-secondary">{{missions.name}}</button>
                    {%endif%}
                    {%endfor%}
                    <button type="button" class="btn btn-secondary">Global</button>
                </div>
            </div>
            <div class="container">
            <div class="row">
                <div class="col-4">
                    <div class="card-body">
                        <h3 class="card-title">Line 2</h5>
                        <div class="row">
                            <div class="btn-group" role="group" aria-label="Basic example">
                                <button type="button" class="btn btn-secondary">24H</button>
                                <button type="button" class="btn btn-primary">7 days</button>
                                <button type="button" class="btn btn-secondary">30 days</button>
                                <button type="button" class="btn btn-secondary">year</button>
                            </div>
                        </div>
                        <p class="card-text">Avergare mission time: 187,7 seconds</p>
                        <p class="card-text">Times launched: 75</p>
                        <p class="card-text">Distance traveled: 137,2 km </p>
                        <a href="#" class="btn btn-primary">Get detailed Pdf Inform</a>

                        </div>
                </div>
                <div class="col-8">
                <h3 class="card-title">Plots</h5>
                    <div class="row">
                        <div class="btn-group" role="group" aria-label="Basic example">
                            <button type="button" class="btn btn-secondary">Avergare mission time</button>
                            <button type="button" class="btn btn-secondary">Times launched</button>
                            <button type="button" class="btn btn-primary">Distance traveled</button>
                        </div>
                        <canvas id="myChart" style="max-width: 500px;"></canvas>
                    </div>
                </div>

            </div>
        </div>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.js"></script>
        <script src="{% static "dashboard/statistics.js" %}" ></script>
        
    {% endblock %}